export const characters = [
  { id: "PRINCE", name: "Prince Escalus", house: "Ruling house of Verona", importance: "primary", descrition: "Ruling Prince of Verona" },
  { id: "PARIS", name: "Count Paris", house: "Ruling house of Verona", importance: "primary", descrition: "Kinsman of Escalus who wishes to marry Juliet." },
  { id: "MERCUTIO", name: "Mercutio", house: "Ruling house of Verona", importance: "primary", descrition: "Another kinsman of Escalus, a friend of Romeo." },
  { id: "PAGE", name: "Page", house: "Ruling house of Verona", importance: "secondary" },
  { id: "CAPULET", name: "Capulet", house: "House of Capulet", importance: "primary", descrition: "Patriarch of the house of Capulet." },
  { id: "LADY CAPULET", name: "Lady Capulet", house: "House of Capulet", importance: "primary", descrition: "Matriarch of the house of Capulet." },
  { id: "JULIET", name: "Juliet Capulet", house: "House of Capulet", importance: "primary", descrition: "13-year-old daughter of Capulet, the play's female protagonist." },
  { id: "TYBALT", name: "Tybalt", house: "House of Capulet", importance: "primary", descrition: "Cousin of Juliet, the nephew of Lady Capulet." },
  { id: "Nurse", name: "The Nurse", house: "House of Capulet", importance: "primary", description: "Juliet's personal attendant and confidante." },
  { id: "PETER", name: "Peter", house: "House of Capulet", importance: "secondary", description: "Servant of the Capulet household." },
  { id: "SAMPSON", name: "Sampson", house: "House of Capulet", importance: "secondary", description: "Servant of the Capulet household." },
  { id: "GREGORY", name: "Gregory", house: "House of Capulet", importance: "secondary", description: "Servant of the Capulet household." },
  { id: "Second Capulet", name: "Second Capulet", house: "House of Capulet", importance: "secondary" },
  { id: "Musician", name: "Musician", house: "House of Capulet", importance: "secondary" },
  { id: "First Musician", name: "First Musician", house: "House of Capulet", importance: "secondary" },
  { id: "Second Musician", name: "Second Musician", house: "House of Capulet", importance: "secondary" },
  { id: "Servant", name: "Servant", house: "House of Capulet", importance: "secondary" },
  { id: "First Servant", name: "First Servant", house: "House of Capulet", importance: "secondary" },
  { id: "Second Servant", name: "Second Servant", house: "House of Capulet", importance: "secondary" },
  { id: "MONTAGUE", name: "Montague", house: "House of Montague", importance: "primary", description: "Patriarch of the house of Montague." },
  { id: "LADY MONTAGUE", name: "Lady Montague", house: "House of Montague", importance: "primary", description: "Matriarch of the house of Montague." },
  { id: "ROMEO", name: "Romeo Montague", house: "House of Montague", importance: "primary", description: "Son of Montague, is the play's male protagonist." },
  { id: "BENVOLIO", name: "Benvolio", house: "House of Montague", importance: "primary", description: "Romeo's cousin and best friend." },
  { id: "BALTHASAR", name: "Balthasar", house: "House of Montague", importance: "secondary", description: "Servant of the Montague household." },
  { id: "ABRAHAM", name: "Abram", house: "House of Montague", importance: "secondary", description: "Servant of the Montague household." },
  { id: "FRIAR LAURENCE", name: "Friar Laurence", house: "Others", importance: "primary", description: "Franciscan friar and Romeo's confidant." },
  { id: "FRIAR JOHN", name: "Friar John", house: "Others", importance: "primary", description: "Sent to deliver Friar Laurence's letter to Romeo." },
  { id: "Apothecary", name: "Apothecary", house: "Others", importance: "primary", description: "Reluctantly sells Romeo poison." },
  { id: "Chorus", name: "Chorus", house: "Others", importance: "primary", description: "Reads a prologue to each of the first two acts." },
  { id: "First Citizen", name: "First Citizen", house: "Others", importance: "secondary" },
  { id: "First Watchman", name: "First Watchman", house: "Others", importance: "secondary" },
  { id: "Second Watchman", name: "Second Watchman", house: "Others", importance: "secondary" },
  { id: "Third Watchman", name: "Third Watchman", house: "Others", importance: "secondary" },
  { id: "Third Musician", name: "Third Musician", house: "Others", importance: "secondary" },
];

export const houses = [
  { house: "Ruling house of Verona", color: "#f4a259" },
  { house: "House of Capulet", color: "#bc4b51" },
  { house: "House of Montague", color: "#5b8e7d" },
  { house: "Others", color: "#474973" },
];