export const characters = [
  { id: "prince", name: "Prince Escalus", house: "Ruling house of Verona", importance: "primary", descrition: "Ruling Prince of Verona" },
  { id: "paris", name: "Count Paris", house: "Ruling house of Verona", importance: "primary", descrition: "Kinsman of Escalus who wishes to marry Juliet." },
  { id: "mercutio", name: "Mercutio", house: "Ruling house of Verona", importance: "primary", descrition: "Another kinsman of Escalus, a friend of Romeo." },
  { id: "page", name: "Page", house: "Ruling house of Verona", importance: "secondary" },
  { id: "capulet", name: "Capulet", house: "House of Capulet", importance: "primary", descrition: "Patriarch of the house of Capulet." },
  { id: "lady_capulet", name: "Lady Capulet", house: "House of Capulet", importance: "primary", descrition: "Matriarch of the house of Capulet." },
  { id: "juliet", name: "Juliet Capulet", house: "House of Capulet", importance: "primary", descrition: "13-year-old daughter of Capulet, the play's female protagonist." },
  { id: "tybalt", name: "Tybalt", house: "House of Capulet", importance: "primary", descrition: "Cousin of Juliet, the nephew of Lady Capulet." },
  { id: "nurse", name: "The Nurse", house: "House of Capulet", importance: "primary", description: "Juliet's personal attendant and confidante." },
  { id: "peter", name: "Peter", house: "House of Capulet", importance: "secondary", description: "Servant of the Capulet household." },
  { id: "sampson", name: "Sampson", house: "House of Capulet", importance: "secondary", description: "Servant of the Capulet household." },
  { id: "gregory", name: "Gregory", house: "House of Capulet", importance: "secondary", description: "Servant of the Capulet household." },
  { id: "second_capulet", name: "second_capulet", house: "House of Capulet", importance: "secondary" },
  { id: "musician", name: "Musician", house: "House of Capulet", importance: "secondary" },
  { id: "first_musician", name: "First Musician", house: "House of Capulet", importance: "secondary" },
  { id: "second_musician", name: "Second Musician", house: "House of Capulet", importance: "secondary" },
  { id: "servant", name: "Servant", house: "House of Capulet", importance: "secondary" },
  { id: "first_servant", name: "First Servant", house: "House of Capulet", importance: "secondary" },
  { id: "second_servant", name: "Second Servant", house: "House of Capulet", importance: "secondary" },
  { id: "montague", name: "Montague", house: "House of Montague", importance: "primary", description: "Patriarch of the house of Montague." },
  { id: "lady_montague", name: "Lady Montague", house: "House of Montague", importance: "primary", description: "Matriarch of the house of Montague." },
  { id: "romeo", name: "Romeo Montague", house: "House of Montague", importance: "primary", description: "Son of Montague, is the play's male protagonist." },
  { id: "benvolio", name: "Benvolio", house: "House of Montague", importance: "primary", description: "Romeo's cousin and best friend." },
  { id: "balthasar", name: "Balthasar", house: "House of Montague", importance: "secondary", description: "Servant of the Montague household." },
  { id: "Abraham", name: "Abram", house: "House of Montague", importance: "secondary", description: "Servant of the Montague household." },
  { id: "friar_laurence", name: "Friar Laurence", house: "Others", importance: "primary", description: "Franciscan friar and Romeo's confidant." },
  { id: "friar_john", name: "Friar John", house: "Others", importance: "primary", description: "Sent to deliver Friar Laurence's letter to Romeo." },
  { id: "apothecary", name: "Apothecary", house: "Others", importance: "primary", description: "Reluctantly sells Romeo poison." },
  { id: "chorus", name: "Chorus", house: "Others", importance: "primary", description: "Reads a prologue to each of the first two acts." },
  { id: "first_citizen", name: "First Citizen", house: "Others", importance: "secondary" },
  { id: "first_watchman", name: "First Watchman", house: "Others", importance: "secondary" },
  { id: "second_watchman", name: "Second Watchman", house: "Others", importance: "secondary" },
  { id: "third_watchman", name: "third_watchman", house: "Others", importance: "secondary" },
  { id: "third_musician", name: "Third Musician", house: "Others", importance: "secondary" },
];

export const houses = [
  { house: "Ruling house of Verona", color: "#f4a259" },
  { house: "House of Capulet", color: "#bc4b51" },
  { house: "House of Montague", color: "#5b8e7d" },
  { house: "Others", color: "#474973" },
];